### ISSUE TITLE
奖品背景颜色设置不生效问题

### ISSUE THREAD

**Issue by aqiusen** [buuing/vue-luck-draw#1]
ctx.fillStyle = awards[i].color || i % 2 == 0 ? '#f8d384' : '#f9e3bb' 这里存在bug ，运算符优先级问题，括号把后面括起来应该可以解决

**Comment by buuing** [comment]
确实, awards[i].color || (i % 2 == 0 ? '#f8d384' : '#f9e3bb')这样果然生效, 你提交代码吧, 我给你合并进去

**Comment by buuing** [comment]
> ctx.fillStyle =奖励[i] .color || 我％2 == 0？'＃f8d384'：'＃f9e3bb'这里存在错误，运算符优先级问题，括号将后面括起来应该可以解决

17778881005@189.cn

**Comment by buuing** [comment]
> ctx.fillStyle =奖励[i] .color || 我％2 == 0？'＃f8d384'：'＃f9e3bb'这里存在错误，运算符优先级问题，括号将后面括起来应该可以解决

确实改成awards[i].color || (i % 2 == 0 ? '#f8d384' : '#f9e3bb')就好了, 你提交代码吧, 我给你合并

**Comment by buuing** [comment]
@aqiusen 确实改成awards[i].color || (i % 2 == 0 ? '#f8d384' : '#f9e3bb')就好了, 你提交代码吧, 我给你合并
