### ISSUE TITLE
转盘奖品文字，怎么自动换行？现在都超出扇形区域了

### ISSUE THREAD

**Issue by haitaoguo** [buuing/vue-luck-draw#11]

**Comment by buuing** [comment]
你好, 使用\n换行

**Comment by haitaoguo** [comment]
接口获取得数据，奖品文字长度不一定  能自动换行吗？

**Comment by haitaoguo** [comment]
> 你好, 使用\n换行
接口获取得数据，奖品文字长度不一定 能自动换行吗？

**Comment by buuing** [comment]
这样啊, 那我一会更新一个v3.0.1版本, 加上自动换行, 一会好了我告诉你

**Comment by haitaoguo** [comment]
> 这样啊, 那我一会更新一个v3.0.1版本, 加上自动换行, 一会好了我告诉你

楼主太棒了，现场解决问题，太感谢了！

**Comment by buuing** [comment]
没事的, 你现在`npm i vue-luck-draw@3.0.1`安装一下看看可以不

**Comment by buuing** [comment]
> 楼主太棒了，现场解决问题，太感谢了！

如果还有关于使用方面的意见或建议都可以说给我, 后续会逐渐进行优化

**Comment by buuing** [comment]
额, 你好, v3.0.1的文字换行有点小问题, 会吞字.....还得麻烦你更新一个v3.0.2
