### ISSUE TITLE
img 的activeSrc 在版本3.0.0不起作用

### ISSUE THREAD

**Issue by 510279293** [buuing/vue-luck-draw#12]

**Comment by buuing** [comment]
嘿嘿, 是的, 因为这个属性是昨晚凌晨刚加的, 太困我就先睡了, 你得更新一下 `npm i vue-luck-draw@3.0.1`

**Comment by 510279293** [comment]
哈哈，大佬辛苦了，Issues回复很快嘛，github上给个👍

**Comment by buuing** [comment]
> 哈哈，大佬辛苦了，Issues回复很快嘛，github上给个👍

额, v3.0.1的文字换行算法有点小问题, 会吞字, 还得麻烦你升级一下v3.0.2
