### ISSUE TITLE
v3.0.2版本  startCallBack 开启转盘方法有问题 点击一次走5遍

### ISSUE THREAD

**Issue by haitaoguo** [buuing/vue-luck-draw#14]
![image](https://user-images.githubusercontent.com/33859222/94105794-a10b0b00-fe6c-11ea-9d94-f64258896986.png)
![image](https://user-images.githubusercontent.com/33859222/94105839-bd0eac80-fe6c-11ea-946b-a7e6955a388a.png)

**Comment by haitaoguo** [comment]
v3.0.2版本

**Comment by buuing** [comment]
好的, 我看一下

**Comment by haitaoguo** [comment]
> 好的, 我看一下
不一定走5遍    但不止一遍

**Comment by buuing** [comment]
> 不一定走5遍    但不止一遍

嗯, 我看了, 这个是因为点击按钮触发回调, 但是游戏开始就不用了触发了, 我加了一个拦截
新版本v3.0.3已修复该问题, 感谢反馈

**Comment by haitaoguo** [comment]
> > 不一定走5遍    但不止一遍
> 
> 嗯, 我看了, 这个是因为点击按钮触发回调, 但是游戏开始就不用了触发了, 我加了一个拦截
> 新版本v3.0.3已修复该问题, 感谢反馈

升级了吗  大佬

**Comment by buuing** [comment]
> 升级了吗 大佬

升级了, 你安装一下最新版 `npm i vue-luck-draw`

**Comment by haitaoguo** [comment]
> > 升级了吗 大佬
> 
> 升级了, 你安装一下最新版 `npm i vue-luck-draw`
大佬，这个能不能 在startCallBack 事件每次只调用一次，因为转盘需要判断用户能不能转，

**Comment by haitaoguo** [comment]
> > 升级了吗 大佬
> 
> 升级了, 你安装一下最新版 `npm i vue-luck-draw`
运行没问题了。 但有个小问题，你试试奖品那块 从接口获取数据后展示，会报个类型错误TypeError: Cannot read property '奖品参数' of undefined"

**Comment by buuing** [comment]
> 运行没问题了。 但有个小问题，你试试奖品那块 从接口获取数据后展示，会报个类型错误TypeError: Cannot read property '奖品参数' of undefined"

嗯, 这个是大转盘内部的图片缓存, 去读取新增奖品, 然后发现数组索引不存在导致的, **这个问题使得新增奖品的图片无法渲染**

我增加了兼容代码来判断, 新版`v3.0.4`已发布, 如果你在奖品里放置了图片, 建议你更新

**Comment by haitaoguo** [comment]
this.$refs.LuckDraw.play(); 启动转盘这个方法，能放到接口回调里吗？因为需要接口判断下用户还能不能转

**Comment by buuing** [comment]
> this.$refs.LuckDraw.play(); 启动转盘这个方法，能放到接口回调里吗？因为需要接口判断下用户还能不能转

可以的, `play()`方法就是为了方便接口判断, 才单独分离出来的

**Comment by haitaoguo** [comment]
![image](https://user-images.githubusercontent.com/33859222/94118811-9c505200-fe80-11ea-9431-899827a18601.png)放到这里，prizeClick 这个接口还是会触发多次

**Comment by haitaoguo** [comment]
![image](https://user-images.githubusercontent.com/33859222/94118890-b722c680-fe80-11ea-84f5-596e99ba9876.png)
放到这里，prizeClick 这个接口还是会触发多次

**Comment by haitaoguo** [comment]
// 转盘操作
        startCallBack() {
            console.log('这里还是会触发多次');
            // 开始旋转 
            prizeClick().then(res => {
                this.$refs.LuckDraw.play();
                this.prizes.forEach((el, index) => {
                    if (el.id === res.data.data.id) {
                        console.log(index)
                        this.getPrizeBase();
                        this.getPrizeRecords();
                        this.$refs.LuckDraw.stop(index);
                    }
                })
})

**Comment by buuing** [comment]
> 放到这里，prizeClick 这个接口还是会触发多次

你看一下`package.json`里面的版本是多少, 或者你可以与我微信交流: new_ldq

**Comment by buuing** [comment]
> 放到这里，prizeClick 这个接口还是会触发多次

哦对的, 我刚反应过来, 因为转盘并没有开始游戏, 所以你可以把他当成一个按钮
如果是拦截用户多次点击, 应该是由你来控制拦截

**Comment by buuing** [comment]
> 放到这里，prizeClick 这个接口还是会触发多次

我这里唯一可以控制的, 就是确保游戏进行中不触发回调

即便是普通的按钮, 你点击多次也会触发多次click事件
