### ISSUE TITLE
开始前的方法

### ISSUE THREAD

**Issue by waveTan** [buuing/vue-luck-draw#2]
我想在点击抽奖前 写一些方法 执行完成了再开始抽奖

**Comment by buuing** [comment]
> 我想在点击抽奖钱 写一些方法 执行完成了再开始抽奖

欢迎欢迎

**Comment by waveTan** [comment]
我不知道这个该怎么实现

**Comment by buuing** [comment]
> 我不知道这个该怎么实现

哦哦, 抱歉我理解错了, 你是想异步的去实现抽奖功能, 我增加了一个方法, 你安装最新版即可

**Comment by buuing** [comment]
> 我不知道这个该怎么实现

this.$refs.你ref的标识.play(中奖的索引)

**Comment by waveTan** [comment]
嗯 谢谢

**Comment by waveTan** [comment]
> > 我不知道这个该怎么实现
> 
> this.$refs.你ref的标识.play(中奖的索引)

非常感谢

**Comment by LoverJoker** [comment]
还有一个问题 activeStyle 中奖标记 好像没有图片这个属性。如果我想要中奖的时候替换图片怎么做呢。
