### ISSUE TITLE
草你吗的

### ISSUE THREAD

**Issue by a550060113** [buuing/vue-luck-draw#3]
浪费老子时间，开始转的回调 已经改变了currIndex，转完指针竟然停在一开始默认的currIndex，去你吗的啊，测都不测完尼玛的，难不成刚进页面就请求？？？日你大爷，给你一🔪。

**Comment by buuing** [comment]
已修复, 升级到 vue-luck-draw@1.2.0 版本可以解决该问题, 另外, 你这脾气一看就是刚入行, 不如省着这点口舌去学习如何PR代码
