### ISSUE TITLE
异步请求目前还是不行

### ISSUE THREAD

**Issue by httpcheck** [buuing/vue-luck-draw#4]
"vue-luck-draw": "^1.2.0",

异步请求好像还不对，给的例子，异步怎么搞？是我哪里姿势不对？

**Comment by buuing** [comment]
在你的 ajax 回调里面使用 this.$refs.luckDraw.play(中奖的索引) 这个方法

**Comment by httpcheck** [comment]
看我提的pr吧，实际情况不能是你这样的，需要点击 圆盘中的抽奖，然后从后端拿到索引后，再开启转动的。

**Comment by buuing** [comment]
要不加个微信聊一下, 我没太懂

**Comment by buuing** [comment]
我微信号: new_ldq

**Comment by buuing** [comment]
已merge
