### ISSUE TITLE
异步抽奖

### ISSUE THREAD

**Issue by cgletufo** [buuing/vue-luck-draw#6]
您好。您插件的异步抽奖，可以在接口返回数据之前，开始转动吗？因为接口延迟的原因会出现点击按钮不能及时转动的情况。

**Comment by buuing** [comment]
> 您好。您插件的异步抽奖，可以在接口返回数据之前，开始转动吗？因为接口延迟的原因会出现点击按钮不能及时转动的情况。

非常抱歉, 目前我天天加班工作较忙, 你可以先加个loading使用, 或者你也可以尝试改造一下提个pr

**Comment by cgletufo** [comment]
因为是小白所以用了一个很笨的方法，解决了一下自己的问题。谢谢给的建议。希望后期可以增加图片支持

**Comment by httpcheck** [comment]
@cgletufo 你是怎么解决的？

**Comment by StarAndSea-zhang** [comment]
哥们儿，before-start事件点击奖盘也能启动，不应该是点击抽奖按钮才启动before-start？且转盘转动时，也就是开始抽奖了，也能通过点击调用before-start事件，可以做个只在按钮范围内且开始抽奖就不调用before-start的限制^v^

**Comment by cgletufo** [comment]
没怎么理解你的想法。

**Comment by cgletufo** [comment]
没怎么理解你的意思。可以在解释一下吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "buuing/vue-luck-draw"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月31日(星期五) 上午10:15
收件人:&nbsp;"buuing/vue-luck-draw"<vue-luck-draw@noreply.github.com&gt;;
抄送:&nbsp;"像风一样的男人"<1079654587@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [buuing/vue-luck-draw] 异步抽奖 (#6)





 
哥们儿，before-start事件点击奖盘也能启动，不应该是点击抽奖按钮才启动before-start？且转盘转动时，也就是开始抽奖了，也能通过点击调用before-start事件，可以做个只在按钮范围内且开始抽奖就不调用before-start的限制^v^

**Comment by httpcheck** [comment]
@StarAndSea-zhang   实际情况是，转盘转动前，需要知道最终的结果，再生成转动轨迹。before-start事件就是这样，先去后端拿到结果，再转动起来。本项目目前没法支持转动中，动态更新最终的中奖结果。

**Comment by buuing** [comment]
> 哥们儿，before-start事件点击奖盘也能启动，不应该是点击抽奖按钮才启动before-start？且转盘转动时，也就是开始抽奖了，也能通过点击之前before-start事件，可以做个只在按钮范围内且开始抽奖就不调用before-start的限制^ v ^

因为当时没考虑网络接口延迟很大的情况, 所以你可以先加个loading, 后期有空了我再进行升级迭代
