### ISSUE TITLE
感觉转的时间有点久

### ISSUE THREAD

**Issue by LongYue9608** [buuing/vue-luck-draw#8]
加一个结束的时间好一点，且每一个奖品块里面加一个奖品Icon图标的设置会好很多

**Comment by buuing** [comment]
> 加一个结束的时间好一点，且每一个奖品块里面加一个奖品Icon图标的设置会好很多

感谢提出意见, 以后迭代会考虑的

**Comment by buuing** [comment]
> 加一个结束的时间好一点，且每一个奖品块里面加一个奖品Icon图标的设置会好很多

现已增加图片引入机制, 并已改善抽奖流程
