### ISSUE TITLE
如何动态控制样式变化，更新转盘绘制呢？

### ISSUE THREAD

**Issue by naive1024** [buuing/vue-luck-draw#9]
![image](https://user-images.githubusercontent.com/29660893/92886306-2098e300-f446-11ea-8fb4-3826f81c85bf.png)
我尝试过计算属性

**Comment by buuing** [comment]
额, 这个问题我考虑到了, 目前这个大转盘正在重构增加功能中, 后续的版本会支持加载图片,  以及动态控制样式, 还有更好的启动停止逻辑, 如果你急用的话, 也可以先尝试自行改造一下

**Comment by buuing** [comment]
@naive1024 最新版`v3.0.8`已完全实现动态改变**边框 / 奖品 / 按钮**等配置项
